site_name: Galaxea Documentation
site_url: https://docs.galaxea.ai
repo_url: https://github.com/userguide-galaxea/Product_User_Guide
site_description: "Galaxea Documentation"
copyright: Copyright &copy; 2023 - 2025 Galaxea
site_author: Galaxea Inc

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
    icon:
         repo: fontawesome/brands/github
    palette:
          primary: black
    font:
        code: Roboto Mono
    plugins:
        - optimize
        - search:
            enabled: true
        - navigation:
            enable: true
        - toc:
            enable: true
        - mkdocs-markdown-it-embed:
            enable: true
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - search.highlight
        - search.inline
        - search.excerpt
#         - navigation.expand
        - navigation.top
        - navigation.sticky
        - toc.follow
        - navigation.tracking
        - navigation.path
extra:
    mathjax:
        enable: true
    social:
        - icon: material/twitter
          link: https://x.com/Galaxea_AI
        - icon: material/github
          link: https://github.com/userguide-galaxea
nav:
  - GUIDE: index.md
  - Galaxea Robot:
      - R1: Introducing_Galaxea_Robot/product_info/R1.md
      - A1: Introducing_Galaxea_Robot/product_info/A1.md
      - Tabletop Teleopration: Guide/Tabletop_Teleopration/Tabletop_Teleopration.md
      - Accessories:
          - Gripper: Introducing_Galaxea_Robot/product_info/A1_accessory_G1.md
          - Dexterous Hand: Introducing_Galaxea_Robot/product_info/Dexterous_Hands.md
  - Galaxea A1 User Guide:
      - Unboxing and Startup Guide: Guide/A1/A1_Getting_Started.md
      - Hardware Introduction: Guide/A1/A1_Hardware_Guide.md
      - Software Introduction: Guide/A1/A1_Software_Guide.md
      - Simulation Tutorial: Guide/A1/A1_Simulation_Tutorial.md
      - FAQ: Guide/A1/A1_FAQ.md
  - Galaxea R1 User Guide:
      - Unboxing and Startup Guide: Guide/R1/R1_Step_by_Step_Guide.md
      - Basic Usage Introduction: Guide/R1/R1_Overview.md
      - Hardware Introduction: Guide/R1/R1_Hardware_Guide.md
      - Software Introduction: Guide/R1/R1_Software_Guide.md
      - Demo Guide: Guide/R1/R1_Demo_Guide.md
      - Simulation Usage Tutorial: Guide/R1/R1_Simulation_Tutorial.md
      - Sensor Calibration Data Collection Method: Guide/R1/R1_Sensor_Calibration_Data_Collection_Method.md
      - R1 Teleop Usage Tutorial: Guide/R1/R1_Teleop_Usage_Tutorial.md
      - R1 VR Teleop Usage Tutorial: Guide/R1/R1_VR_Teleop_Usage_Tutorial.md
      - R1 Autonomous Navigation System Usage Tutorial: Guide/R1/R1_Autonomous_Navigation_System_Usage_Tutorial.md
  - Galaxea R1 Software Changelog:
        - V1.1.0: Guide/R1/R1_Software_Changelog/v1.1.0.md
        - V1.0.4: Guide/R1/R1_Software_Changelog/v1.0.4.md
  - Galaxea R1 Lite User Guide:
        - Unboxing and Startup Guide: Guide/R1Lite/R1Lite_Unboxing_Startup_Guide.md
        - Basic Usage Introduction: Guide/R1Lite/R1Lite_Basic_Usage_Introduction.md
        - Hardware Introduction: Guide/R1Lite/R1Lite_Hardware_Introduction.md
        - Software Introduction: Guide/R1Lite/R1Lite_Software_Introduction.md
        - Wheel Motor Zero-Point Calibration Instruction: Guide/R1Lite/R1Lite_Wheel_Motor_Calibration.md

extra_css:
  - styles.css
  - Introducing_Galaxea_Robot/simple_intro.css
  - Introducing_Galaxea_Robot/detail_intro.css

markdown_extensions:
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            GUIDE: 导航
            Galaxea Robot: 产品信息
            Galaxea A1 User Guide: Galaxea A1 用户手册
            Galaxea R1 User Guide: Galaxea R1 用户手册
            Galaxea B1 User Guide: Galaxea B1 用户手册
            Galaxea R1 Lite User Guide: Galxea R1 Lite 用户手册
            Getting Started: 开箱启动指南
            Hardware Introduction: 硬件介绍
            Software Introduction: 软件介绍
            Simulation Usage Tutorial: 仿真使用教程
            Accessories: 配件
            Gripper: 夹爪
            Dexterous Hand: 灵巧手
            Tabletop Teleopration: 桌面遥操
            Step-By-Step Startup Guide: 开箱启动指南
            Unboxing and Startup Guide: 开箱启动指南
            Overview: 快速入门
            Galaxea R1 Software Changelog: Galaxea R1 软件版本更新日志
            Simulation Tutorial: 仿真使用教程
            Sensor Calibration Data Collection Method: 传感器标定数据采集方法
            R1 Teleop Usage Tutorial: R1 Teleop 同构遥操作教程
            R1 VR Teleop Usage Tutorial: R1 VR Teleop 遥操作教程
            R1 Autonomous Navigation System Usage Tutorial: R1 自主导航系统使用教程
            Demo Guide: Demo演示指南
            Hardware Introduction: 硬件介绍
            Software Introduction: 软件介绍
            Basic Usage Introduction: 基础使用介绍
            Wheel Motor Zero-Point Calibration Instruction: 舵轮电机零点标定说明
            FAQ: 常见问题
