site_name: GALAXEA
site_url: https://docs.galaxea.ai
repo_url: https://github.com/userguide-galaxea/Product_User_Guide
site_description: "Galaxea"
copyright: Copyright &copy; 2023 - 2024 Galaxea
site_author: Galaxea Inc

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
    icon:
         repo: fontawesome/brands/github
    palette:
          primary: black
    font:
        code: Roboto Mono
    plugins:
        - optimize
        - search:
            enabled: true
        - navigation:
            enable: true
        - toc:
            enable: true
        - mkdocs-markdown-it-embed:
            enable: true
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - search.highlight
        - search.inline
        - search.excerpt
#         - navigation.expand
        - navigation.top
        - toc.follow
        - navigation.tracking
        - navigation.path
extra:
    mathjax:
        enable: true
    social:
        - icon: material/twitter
          link: https://x.com/Galaxea_AI
        - icon: material/github
          link: https://github.com/userguide-galaxea
nav:
  - GUIDE: index.md
  - Galaxea Robot:
      - R1: Introducing_Galaxea_Robot/product_info/R1.md
      - A1: Introducing_Galaxea_Robot/product_info/A1.md
      - Tabletop Teleopration: Guide/Tabletop_Teleopration/Tabletop_Teleopration.md
      - Accessories:
          - Gripper: Introducing_Galaxea_Robot/product_info/A1_accessory_G1.md
          - Dexterous Hand: Introducing_Galaxea_Robot/product_info/Dexterous_Hands.md
  - Galaxea A1 User Guide:
      - Getting Started: Guide/A1/Getting_Started.md
      - Hardware Guide: Guide/A1/Hardware_Guide.md
      - Software Guide: Guide/A1/Software_Guide.md
      - Simulation Isaac Sim Usage Tutorial: Guide/A1/Simulation_Isaac_Sim_Tutorial.md
  - Galaxea R1 User Guide:
      - Overview: Guide/R1/R1_Overview.md
      - Hardware Guide: Guide/R1/Hardware_Guide.md
      - Software Guide: Guide/R1/Software_Guide.md
      - Step-By-Step Startup Guide: Guide/R1/R1_Step_by_Step_Guide.md
      - Demo: Guide/R1/R1_demo_test.md
      - Simulation Usage Tutorial: Guide/R1/Simulation_Isaac_Lab_Tutorial.md
      - Sensor Calibration Data Collection Method: Guide/R1/R1_Sensor_Calibration_Data_Collection_Method.md
      - R1 Teleop Usage Tutorial: Guide/R1/R1_Teleop_Usage_Tutorial.md
      - R1 VR Teleop Usage Tutorial: Guide/R1/R1_VR_Teleop_Usage_Tutorial.md
      - R1 Autonomous Navigation System Usage Tutorial: Guide/R1/R1_Autonomous_Navigation_System_Usage_Tutorial.md
  - Galaxea R1 Software Changelog:
        - V1.1.0: Guide/R1/R1_Software_Changelog/v1.1.0.md
        - V1.0.4: Guide/R1/R1_Software_Changelog/v1.0.4.md
#   - Galaxea B1 User Guide:
#       - Getting Started: Guide/B1/B1_Getting_Started.md
#       - Hardware Guide: Guide/B1/B1_Hardware_Guide.md
#       - Software Guide: Guide/B1/B1_Software_Guide.md

extra_css:
  - styles.css
  - Introducing_Galaxea_Robot/simple_intro.css
  - Introducing_Galaxea_Robot/detail_intro.css

markdown_extensions:
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            GUIDE: 导航
            Galaxea Robot: 产品信息
            Galaxea A1 User Guide: Galaxea A1 用户手册
            Galaxea R1 User Guide: Galaxea R1 用户手册
            Galaxea B1 User Guide: Galaxea B1 用户手册
            Getting Started: 快速入门
            Hardware Guide: 硬件手册
            Software Guide: 软件手册
            Simulation Isaac Sim Usage Tutorial: 仿真 Isaac Sim 使用教程
            Simulation Isaac Lab Usage Tutorial: 仿真 Isaac Lab 使用教程
            Accessories: 配件
            Gripper: 夹爪
            Dexterous Hand: 灵巧手
            Tabletop Teleopration: 桌面遥操
            Step-By-Step Startup Guide: 开箱指南
            Overview: 快速入门
            Galaxea R1 Software Changelog: Galaxea R1 软件版本更新日志
            Simulation Usage Tutorial: 仿真使用教程
            Sensor Calibration Data Collection Method: 传感器标定数据采集方法
            R1 Teleop Usage Tutorial: R1 Teleop 同构遥操作教程
            R1 VR Teleop Usage Tutorial: R1 VR Teleop 遥操作教程
            R1 Autonomous Navigation System Usage Tutorial: R1 自主导航系统使用教程
