site_name: Galaxea Documentation
site_url: https://docs.galaxea.ai
repo_url: https://github.com/userguide-galaxea/Product_User_Guide
site_description: "Galaxea Documentation"
copyright: Copyright &copy; 2023 - 2025 Galaxea
site_author: Galaxea Inc

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
    icon:
         repo: fontawesome/brands/github
    palette:
          primary: black
    font:
        code: Roboto Mono
    plugins:
        - optimize
        - search:
            enabled: true
        - navigation:
            enable: true
        - toc:
            enable: true
        - mkdocs-markdown-it-embed:
            enable: true
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - search.highlight
        - search.inline
        - search.excerpt
#         - navigation.expand
        - navigation.top
        - navigation.sticky
        - toc.follow
        - navigation.tracking
        - navigation.path
extra:
    mathjax:
        enable: true
    social:
        - icon: material/twitter
          link: https://x.com/Galaxea_AI
        - icon: material/github
          link: https://github.com/userguide-galaxea
nav:
  - GUIDE: index.md
  - Galaxea Robot:
      - R1: Introducing_Galaxea_Robot/product_info/R1.md
      - A1: Introducing_Galaxea_Robot/product_info/A1.md
      - Tabletop Teleopration: Guide/Tabletop_Teleopration/Tabletop_Teleopration.md
      - Accessories:
          - Gripper: Introducing_Galaxea_Robot/product_info/A1_accessory_G1.md
          - Dexterous Hand: Introducing_Galaxea_Robot/product_info/Dexterous_Hands.md
  - Galaxea A1 User Guide:
      - Unbox and Installation Guide: Guide/A1/A1_Getting_Started.md
      - Hardware Introduction: Guide/A1/A1_Hardware_Guide.md
      - Software Introduction: Guide/A1/A1_Software_Guide.md
      - Simulation Usage Instruction: Guide/A1/A1_Simulation_Tutorial.md
      - FAQ: Guide/A1/A1_FAQ.md
  - Galaxea A1XY User Guide:
      - Getting Started: Guide/A1XY/A1XY_Getting_Started.md
      - Unbox and Installation Guide: Guide/A1XY/A1XY_Unbox_Guide.md
      - Startup and Demo Guide: Guide/A1XY/A1XY_Startup_Demo_Guide.md
      - Hardware Introduction: Guide/A1XY/A1XY_Hardware_Introduction.md
      - Software Introduction: Guide/A1XY/A1XY_Software_Introduction.md
      # - Simulation Usage Instruction: Guide/A1/A1_Simulation_Tutorial.md
      # - FAQ: Guide/A1/A1_FAQ.md
  - Galaxea R1 User Guide:
      - Getting Started: Guide/R1/R1_Overview.md
      - Unbox and Startup Guide: Guide/R1/R1_Step_by_Step_Guide.md
      - Demo Guide: Guide/R1/R1_Demo_Guide.md
      - Hardware Introduction: Guide/R1/R1_Hardware_Guide.md
      - Software Introduction: Guide/R1/R1_Software_Guide.md
      - Simulation Usage Instruction: Guide/R1/R1_Simulation_Tutorial.md
      - Sensor Calibration Data Collection Method: Guide/R1/R1_Sensor_Calibration_Data_Collection_Method.md
      - Teleop Usage Tutorial: Guide/R1/R1_Teleop_Usage_Tutorial.md
      - VR Teleop Usage Tutorial: Guide/R1/R1_VR_Teleop_Usage_Tutorial.md
      - Autonomous Navigation System Usage Tutorial: Guide/R1/R1_Autonomous_Navigation_System_Usage_Tutorial.md
    #   - FAQ: Guide/R1/R1_FAQ.md
      - Software Changelog: Guide/R1/R1_Software_Changelog/R1_changelog.md
  - Galaxea R1 Lite User Guide:
        - Getting Started: Guide/R1Lite/R1Lite_Getting_Started.md
        - Unbox and Startup Guide: Guide/R1Lite/R1Lite_Unbox_Startup_Guide.md
        - Hardware Introduction: Guide/R1Lite/R1Lite_Hardware_Introduction.md
        - Software Introduction: Guide/R1Lite/R1Lite_Software_Introduction.md
        - Wheel Motor Zero-Point Calibration Instruction: Guide/R1Lite/R1Lite_Wheel_Motor_Calibration.md
  - Galaxea R1 Pro User Guide:
        - Getting Started: Guide/R1Pro/R1Pro_Getting_Started.md
        - Unbox and Startup Guide: Guide/R1Pro/R1Pro_Unbox_Startup_Guide.md
        - Demo Guide: Guide/R1Pro/R1Pro_Demo_Guide.md
        - Hardware Introduction: Guide/R1Pro/R1Pro_Hardware_Introduction.md
        - Software Introduction: Guide/R1Pro/R1Pro_Software_Guide.md
        - VR Teleop Usage Tutorial: Guide/R1Pro/R1Pro_VR_Teleop_Usage_Tutorial.md
        - Software Changelog: Guide/R1Pro/R1Pro_Software_Changelog/R1Pro_changelog.md

extra_css:
  - styles.css
  - Introducing_Galaxea_Robot/simple_intro.css
  - Introducing_Galaxea_Robot/detail_intro.css

markdown_extensions:
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            GUIDE: 首页
            Galaxea Robot: 产品信息
            Galaxea A1 User Guide: Galaxea A1 用户手册
            Galaxea A1XY User Guide: Galaxea A1XY 用户手册
            Galaxea R1 User Guide: Galaxea R1 用户手册
            Galaxea R1 Pro User Guide: Galaxea R1 Pro 用户手册
            Galaxea R1 Lite User Guide: Galaxea R1 Lite 用户手册
            Accessories: 配件
            Gripper: 夹爪
            Dexterous Hand: 灵巧手
            Tabletop Teleopration: 桌面遥操
            Getting Started: 快速开始
            Overview: 快速开始
            Hardware Introduction: 硬件介绍
            Software Introduction: 软件介绍
            # Step-By-Step Startup Guide: 开箱启动指南
            Unbox and Startup Guide: 开箱启动指南
            Startup and Demo Guide: 启动与Demo演示指南
            Unbox and Installation Guide: 开箱安装指南
            Demo Guide: Demo演示指南
            Software Changelog: 软件版本更新日志
            Simulation Usage Instruction: 仿真平台使用说明
            Sensor Calibration Data Collection Method: 传感器标定数据采集方法
            Teleop Usage Tutorial: Teleop 同构遥操作教程
            VR Teleop Usage Tutorial: VR Teleop 遥操作教程
            Autonomous Navigation System Usage Tutorial: 自主导航系统使用教程
            Wheel Motor Zero-Point Calibration Instruction: 舵轮电机零点标定说明
            FAQ: 常见问题
